In [39]:
import pandas as pd
from paths import *

In [40]:
filepath = src_dir + "HKSL_Prediction_Cynthia_train.xlsx"
# Read the Excel file
df = pd.read_excel(filepath)
filtered_df = df[(df['side'] == 'Right') & (df['missing_detection'] == 1)]

In [41]:
new_filtered_df = filtered_df.drop_duplicates(subset='sign_name', keep='first', inplace=False)

In [36]:
filtered_df

,Unnamed: 0,sign_name,side,frame_idx,target,predicted,is_correct,anno,missing_detection
6,6,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,6,6,x,0,HS,1
9,9,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,9,6,x,0,HS,1
10,10,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,10,6,x,0,HS,1
11,11,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,11,6,x,0,HS,1
12,12,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,12,6,x,0,HS,1
...,...,...,...,...,...,...,...,...,...
129035,129035,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,71,y,x,0,HS,1
129036,129036,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,72,y,x,0,HS,1
129037,129037,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,73,y,x,0,HS,1
129038,129038,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,74,y,x,0,HS,1
129039,129039,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,75,y,x,0,HS,1

In [42]:
new_filtered_df

,Unnamed: 0,sign_name,side,frame_idx,target,predicted,is_correct,anno,missing_detection
6,6,HKSL_lesson_only406-BEST_FRIENDS-0QRR-882,Right,6,6,x,0,HS,1
156,156,HKSL_lesson_only82-PLAY_VIDEO_GAME-0ST9-545,Right,0,1,x,0,HS,1
414,414,B_01_079-NOTHING-0KC7-67,Right,36,O,?,0,HS,1
600,600,HKSL_lesson_only374-HEALTHCARE-14DB-849,Right,0,y,x,0,HS,1
785,785,C_03_009-^INDIAN_2-0KRG-395,Right,15,D,x,0,HS,1
...,...,...,...,...,...,...,...,...,...
128187,128187,C_03_012-SUSPECT-0OFN-399,Right,1,f,x,0,HS,1
128390,128390,C_01_019-UGLY-0QH3-246,Right,16,P,x,0,HS,1
128603,128603,HKSL_lesson_only10-SIGN_LANGUAGE-0OIB-468,Right,37,>,x,0,HS,1
128802,128802,C_03_080-FUTURE-0PPA-450,Right,10,",",x,0,HS,1
128964,128964,HKSL_lesson_only72-VOLLEYBALL-0OSI-535,Right,0,y,x,0,HS,1

In [43]:
target_counts = new_filtered_df['target'].value_counts()
print(target_counts)

x    103
B     60
6     33
>     32
C     30
?     27
2     25
y     24
Y     23
O     21
1     21
:     20
D     20
L     19
P     18
A     17
f     17
M     16
<     15
)     15
w     14
T     13
,     12
-     11
b     11
3     10
W     10
u      7
5      7
I      7
z      6
n      5
g      5
J      5
o      5
j      5
;      4
4      4
Z      3
r      3
l      2
0      2
h      2
X      2
v      2
t      1
=      1
N      1
8      1
m      1
s      1
F      1
V      1
d      1
k      1
Name: target, dtype: int64

In [44]:
target_counts = filtered_df['target'].value_counts()
print(target_counts)

x    6445
B    3630
6    1999
>    1749
?    1655
C    1626
2    1578
y    1496
Y    1408
1    1254
D    1199
:    1118
O    1103
f    1055
L    1027
P    1006
<     963
A     952
T     948
)     925
M     924
w     889
,     764
b     711
3     669
-     621
W     537
I     466
u     442
z     422
5     419
J     355
n     312
j     312
;     271
o     261
4     255
g     250
Z     205
r     166
X     149
h     138
l     134
s     107
0      99
v      95
V      92
m      84
t      78
F      71
=      65
8      54
d      40
N      37
k      24
Name: target, dtype: int64

In [45]:
target_counts_df = pd.DataFrame(target_counts)
target_counts_df = target_counts_df.rename(columns={'target': 'count'})
target_counts_df.index.name = 'target'
target_counts_df.reset_index(inplace=True)
target_counts_df

   target  count
0       x   6445
1       B   3630
2       6   1999
3       >   1749
4       ?   1655
5       C   1626
6       2   1578
7       y   1496
8       Y   1408
9       1   1254
10      D   1199
11      :   1118
12      O   1103
13      f   1055
14      L   1027
15      P   1006
16      <    963
17      A    952
18      T    948
19      )    925
20      M    924
21      w    889
22      ,    764
23      b    711
24      3    669
25      -    621
26      W    537
27      I    466
28      u    442
29      z    422
30      5    419
31      J    355
32      n    312
33      j    312
34      ;    271
35      o    261
36      4    255
37      g    250
38      Z    205
39      r    166
40      X    149
41      h    138
42      l    134
43      s    107
44      0     99
45      v     95
46      V     92
47      m     84
48      t     78
49      F     71
50      =     65
51      8     54
52      d     40
53      N     37
54      k     24

In [47]:
target_counts_df['unmarked'] = target_counts_df['target'].apply(lambda x: 1 if x in ['B', 'y', '2', 'C', '6', '>'] else 0)

In [48]:
target_counts_df

   target  count  unmarked
0       x   6445         0
1       B   3630         1
2       6   1999         1
3       >   1749         1
4       ?   1655         0
5       C   1626         1
6       2   1578         1
7       y   1496         1
8       Y   1408         0
9       1   1254         0
10      D   1199         0
11      :   1118         0
12      O   1103         0
13      f   1055         0
14      L   1027         0
15      P   1006         0
16      <    963         0
17      A    952         0
18      T    948         0
19      )    925         0
20      M    924         0
21      w    889         0
22      ,    764         0
23      b    711         0
24      3    669         0
25      -    621         0
26      W    537         0
27      I    466         0
28      u    442         0
29      z    422         0
30      5    419         0
31      J    355         0
32      n    312         0
33      j    312         0
34      ;    271         0
35      o    261         0
36      4    255         0
37      g    250         0
38      Z    205         0
39      r    166         0
40      X    149         0
41      h    138         0
42      l    134         0
43      s    107         0
44      0     99         0
45      v     95         0
46      V     92         0
47      m     84         0
48      t     78         0
49      F     71         0
50      =     65         0
51      8     54         0
52      d     40         0
53      N     37         0
54      k     24         0

In [49]:
correlation = target_counts_df['count'].corr(target_counts_df['unmarked'])
correlation

0.4196024678835038

In [50]:
test_filepath = src_dir + "HKSL_Prediction_Cynthia_test_mono.xlsx"
# Read the Excel file
test_df = pd.read_excel(test_filepath)
test_filtered_df = test_df[(test_df['side'] == 'Right') & (test_df['missing_detection'] == 1)]

In [52]:
test_target_counts = test_filtered_df['target'].value_counts()
print(test_target_counts)

B    380
x    291
y    211
f    160
2    152
C    151
:    129
?    120
z    108
)     92
A     77
5     74
6     68
L     65
T     65
;     60
w     57
k     55
O     54
>     51
J     50
<     40
P     38
Name: target, dtype: int64

In [53]:
test_target_counts_df = pd.DataFrame(test_target_counts)
test_target_counts_df = test_target_counts_df.rename(columns={'target': 'count'})
test_target_counts_df.index.name = 'target'
test_target_counts_df.reset_index(inplace=True)
test_target_counts_df

   target  count
0       B    380
1       x    291
2       y    211
3       f    160
4       2    152
5       C    151
6       :    129
7       ?    120
8       z    108
9       )     92
10      A     77
11      5     74
12      6     68
13      L     65
14      T     65
15      ;     60
16      w     57
17      k     55
18      O     54
19      >     51
20      J     50
21      <     40
22      P     38

In [54]:
test_target_counts_df['unmarked'] = test_target_counts_df['target'].apply(lambda x: 1 if x in ['B', 'y', '2', 'C', '6', '>'] else 0)
test_target_counts_df

   target  count  unmarked
0       B    380         1
1       x    291         0
2       y    211         1
3       f    160         0
4       2    152         1
5       C    151         1
6       :    129         0
7       ?    120         0
8       z    108         0
9       )     92         0
10      A     77         0
11      5     74         0
12      6     68         1
13      L     65         0
14      T     65         0
15      ;     60         0
16      w     57         0
17      k     55         0
18      O     54         0
19      >     51         1
20      J     50         0
21      <     40         0
22      P     38         0

In [56]:
correlation = test_target_counts_df['count'].corr(test_target_counts_df['unmarked'])
correlation

0.4142446349431196